version: "3.9"
services:
  app:
    build:
      context: .
      platforms:
        - linux/amd64
    container_name: film_bot
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/film_database
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Пароль для root
      MYSQL_USER: new_user                # Пользователь
      MYSQL_PASSWORD: secure_password        # Пароль для пользователя
      MYSQL_DATABASE: film_database
      TZ: "Europe/Moscow"
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql_data/data
    platform: linux/amd64

volumes:
  mysql_data:
